server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: main_service_circuitbreaker_route
          uri: lb://main-service
          predicates:
            - Path=/categories/**,/compilations/**,/events/**,/users/**,/admin/**
          filters:
            - CircuitBreaker=myCircuitBreaker