server:
  port: 0

kafka:
  bootstrap-servers: localhost:9092
  key_serializer_class: org.apache.kafka.common.serialization.StringSerializer
  value_serializer_class: ru.yandex.practicum.mapper.GeneralAvroSerializer
  topic:
    action: stats.user-actions.v1

grpc:
  server:
    port: 0