spring:
  application:
    name: stats-server
  config:
    import: "configserver:http://${CONFIG_HOSTNAME:localhost}:8888"
    cloud:
      discovery:
        enabled: true
        serviceId: CONFIG-SERVER
        fail-fast: true
        retry:
          useRandomPolicy: true
          max-interval: 6000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${eureka.instance.port:8761}/eureka/
