server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: stats-server
  datasource:
    driverClassName: org.postgresql.Driver
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/stats
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  sql:
    init:
      mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${eureka.instance.port:8761}/eureka/