server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: comment-service
  datasource:
    driverClassName: org.postgresql.Driver
    username: login
    password: password
    url: jdbc:postgresql://localhost:6542/comment_db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  sql:
    init:
      mode: always